[package]
name = "metal-crusher"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
rodio = "0.20.1"
x11 = { version = "2.21.0", features = [ "xlib" ] }
xdg-user = "0.2.1"
zbus = "5.5.0"
