name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install ALSA dev libs
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y libasound2-dev
        sudo apt-get install -y alsa-lib
        sudo apt-get install -y libzita-alsa-pcmi-dev
        sudo apt-get install -y pkg-config
        sudo apt-get install librust-alsa-sys-dev
        sudo apt install --reinstall -y libasound2-dev
        sudo apt-get install -y libudev-dev

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    
    - uses: actions/upload-artifact@v4
      with: 
        name: Metal Crusher
        path: ./target/release/metal-crusher
